#!/usr/bin/env bash
# Builds the PS2 core (Play! + WebStationX patches) to public/cores/play/.
#
#   engine/play/build.sh [--clean]
#
# Needs git, cmake, ninja and an activated Emscripten SDK (emcc on PATH, e.g. `source <emsdk>/emsdk_env.sh`).
# Sources are cloned to $PLAY_SRC (default work/play-src) at the pinned upstream commit, the patches in
# engine/play/patches are applied on a local `webstationx` branch, and the result is copied into the app.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SRC="${PLAY_SRC:-$ROOT/work/play-src}"
OUT="$ROOT/public/cores/play"

PLAY_REPO=https://github.com/jpd002/Play-.git
PLAY_COMMIT=83700b2c31e593bc94e845b4b31b797be84dda59 # 0.77-12
CODEGEN_COMMIT=a5009f7dca062695b8e5aebbd71e67b4ddfa9251
EMSDK_TESTED=6.0.10

command -v emcc >/dev/null || { echo "emcc not found: activate the Emscripten SDK ($EMSDK_TESTED tested)" >&2; exit 1; }
command -v ninja >/dev/null || { echo "ninja not found (pip install ninja)" >&2; exit 1; }

if [ "${1:-}" = "--clean" ]; then rm -rf "$SRC"; fi

if [ ! -d "$SRC/.git" ]; then
  git clone "$PLAY_REPO" "$SRC"
fi

apply_patches() { # <repo dir> <base commit> <patch dir>
  local dir="$1" base="$2" patches="$3"
  if git -C "$dir" rev-parse -q --verify webstationx >/dev/null; then
    # Rebuild the branch when the patch set changed.
    local want have
    want=$(cat "$patches"/*.patch | git patch-id --stable | awk '{print $1}' | sort | tr -d '\n')
    have=$(git -C "$dir" format-patch --stdout "$base..webstationx" -- . ':!deps/CodeGen' | git patch-id --stable | awk '{print $1}' | sort | tr -d '\n')
    if [ "$want" = "$have" ]; then
      git -C "$dir" checkout -q webstationx
      return
    fi
    git -C "$dir" checkout -q --detach "$base"
    git -C "$dir" branch -q -D webstationx
  fi
  git -C "$dir" checkout -q -B webstationx "$base"
  git -C "$dir" -c user.name=wsx -c user.email=wsx@localhost am -q --keep-cr "$patches"/*.patch
}

git -C "$SRC" fetch -q origin "$PLAY_COMMIT" 2>/dev/null || true
git -C "$SRC" checkout -q --detach "$PLAY_COMMIT" 2>/dev/null || git -C "$SRC" checkout -q webstationx
git -C "$SRC" submodule update --init --recursive -q
apply_patches "$SRC/deps/CodeGen" "$CODEGEN_COMMIT" "$HERE/patches/codegen"
apply_patches "$SRC" "$PLAY_COMMIT" "$HERE/patches/play"
# The Play! patches don't carry the CodeGen gitlink: keep the patched CodeGen checked out.
git -C "$SRC/deps/CodeGen" checkout -q webstationx

cd "$SRC"
if [ ! -f build_cmake/build/wasm-ninja/build.ninja ]; then
  emcmake cmake --preset wasm-ninja
fi
cmake --build --preset wasm-ninja-release --target Play

BUILT="$SRC/build_cmake/build/wasm-ninja/Source/ui_js"
# GSH_OpenGLJs posts frames with Emscripten's "callHandler" worker message (cmd 9); make sure the glue
# generated by this Emscripten still dispatches it that way.
grep -q 'case 9:Module\[d.handler\]' "$BUILT/Play.js" || { echo "Emscripten worker message layout changed: update wsx_gs_present (GSH_OpenGLJs.cpp)" >&2; exit 1; }

mkdir -p "$OUT"
cp "$BUILT/Play.js" "$BUILT/Play.wasm" "$OUT/"
# The server caches /cores/ as immutable: the app loads /cores/play/<hash>/ for the module and workers.
VERSION=$(cat "$OUT/Play.js" "$OUT/Play.wasm" | sha1sum | cut -c1-12)
printf "// Written by engine/play/build.sh: cache-busts the PS2 core (public/cores/play).\nexport const PS2_CORE_VERSION = '%s';\n" "$VERSION" > "$ROOT/src/emu/ps2/core-version.ts"
echo "PS2 core $VERSION -> $OUT ($(du -h "$OUT/Play.wasm" | cut -f1) wasm)"
